apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clone-mysql-pv-claim 
  namespace: wordpress
spec:
  storageClassName: wordpress
  dataSource:
    name: mysql-pv-claim
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
