apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: my-snapshot
  namespace: wordpress
spec:
  volumeSnapshotClassName: my-snapshot-class
  source:
    persistentVolumeClaimName: mysql-pv-claim
